# tasks file for roles/grafana
- name: Import Grafana GPG key
  ansible.builtin.apt_key:
    url: https://packages.grafana.com/gpg.key
    state: present

- name: Add Grafana APT repository
  ansible.builtin.apt_repository:
    repo: 'deb https://packages.grafana.com/oss/deb stable main'
    state: present
    filename: 'grafana'

- name: Update APT cache
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install Grafana
  ansible.builtin.apt:
    name: grafana
    state: present

- name: Ensure Grafana service is enabled and started
  ansible.builtin.service:
    name: grafana-server
    state: started
    enabled: yes
