all:
  children:
    prometheus:
      hosts:
        prometheus_server_1:
          ansible_host: 3.82.195.251
    grafana:
      hosts:
        grafana_server_1:
          ansible_host: 44.211.145.79
