all:
  vars:
    ansible_connection: local  # Run everything on the same VM (no SSH needed)
  children:
    prometheus:
      hosts:
        localhost: {}  # Simulate Server B on local
    grafana:
      hosts:
        localhost: {}  # Simulate Server C on local
    monitored:
      hosts:
        localhost: {}  # Simulate slaves on local
# Add additional monitored servers as needed
