# tasks file for roles/node_exporter
---
- name: Download node_exporter
  get_url:
    url: "https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz"
    dest: "/tmp/node_exporter.tar.gz"

- name: Extract node_exporter
  unarchive:
    src: "/tmp/node_exporter.tar.gz"
    dest: "/tmp"
    remote_src: yes
    creates: "/tmp/node_exporter-{{ node_exporter_version }}.linux-amd64"

- name: Move node_exporter binary to /usr/local/bin
  command: mv /tmp/node_exporter-{{ node_exporter_version }}.linux-amd64/node_exporter /usr/local/bin/node_exporter
  args:
    creates: /usr/local/bin/node_exporter

- name: Ensure node_exporter is executable
  file:
    path: /usr/local/bin/node_exporter
    mode: '0755'

- name: Create systemd service file for node_exporter
  template:
    src: node_exporter.service.j2
    dest: /etc/systemd/system/node_exporter.service
  notify: reload systemd

- name: Enable and start node_exporter
  systemd:
    name: node_exporter
    enabled: yes
    state: started
